---
# tasks file for glance DB Setup

- name: DB sync for glance.
  command: >
    glance-manage db_sync
  become: yes
  become_user: "{{ glance_system_user_name }}"
  ignore_errors: True
  run_once: True
