---
# tasks file for ansible-role-openstack-glance

# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: glance_service_setup.yml
  run_once: True

# Setup/Install tasks.
- include: glance_install_RedHat.yml
  when: ansible_os_family == 'RedHat'

# Configure tasks.
- include: glance_configure.yml

# DB tasks.
- include: glance_db_setup.yml

# Finalize installation tasks.
- include: glance_post_install.yml
